src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nomFormation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $objectif_global;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFormation(): ?string
    {
        return $this->nomFormation;
    }

    public function setNomFormation(string $nomFormation): self
    {
        $this->nomFormation = $nomFormation;

        return $this;
    }

    public function getObjectifGlobal(): ?string
    {
        return $this->objectif_global;
    }

    public function setObjectifGlobal(?string $objectif_global): self
    {
        $this->objectif_global = $objectif_global;

        return $this;
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomFormation')
            ->add('objectif_global')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formation")
 */
class FormationController extends AbstractController
{
    /**
     * @Route("/", name="formation_index", methods={"GET"})
     */
    public function index(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formation_show", methods={"GET"})
     */
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formation_delete", methods={"POST"})
     */
    public function delete(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/formation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/formation/edit.html.twig
{% block title %}Edit Formation{% endblock %}

{% block body %}
    <h1>Edit Formation</h1>

    {{ include('formation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('formation_index') }}">back to list</a>

    {{ include('formation/_delete_form.html.twig') }}
{% endblock %}

templates/formation/index.html.twig
{% block title %}Formation index{% endblock %}

{% block body %}
    <h1>Formation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>NomFormation</th>
                <th>Objectif_global</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for formation in formations %}
            <tr>
                <td>{{ formation.id }}</td>
                <td>{{ formation.nomFormation }}</td>
                <td>{{ formation.objectifGlobal }}</td>
                <td>
                    <a href="{{ path('formation_show', {'id': formation.id}) }}">show</a>
                    <a href="{{ path('formation_edit', {'id': formation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('formation_new') }}">Create new</a>
{% endblock %}

templates/formation/new.html.twig
{% block title %}New Formation{% endblock %}

{% block body %}
    <h1>Create new Formation</h1>

    {{ include('formation/_form.html.twig') }}

    <a href="{{ path('formation_index') }}">back to list</a>
{% endblock %}

templates/formation/show.html.twig
{% block title %}Formation{% endblock %}

{% block body %}
    <h1>Formation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formation.id }}</td>
            </tr>
            <tr>
                <th>NomFormation</th>
                <td>{{ formation.nomFormation }}</td>
            </tr>
            <tr>
                <th>Objectif_global</th>
                <td>{{ formation.objectifGlobal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('formation_index') }}">back to list</a>

    <a href="{{ path('formation_edit', {'id': formation.id}) }}">edit</a>

    {{ include('formation/_delete_form.html.twig') }}
{% endblock %}